server:
  port: 8777
spring:
  application:
    name: abc

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

eureka:
  client:
    service-url:
      defaultZone:  http://10.10.11.90:8761/eureka

feign:
  hystrix:
    enabled: true
